### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Matthww** [flaxues/PyShit#3]
- [ ] Options
- [ ] More screen cmd
- [ ] Add encryption
- [ ] GUI for exobyte
- [ ] Realtime clock
- [x] Weather API command
- [ ] BTC API command
- [ ] Messenger/chat function
- [ ] File protector
- [ ] Ez social media hub
- [ ] command - Features later
- [x] Password login change
- [x] Password login store file
- [x] Add colors!

**Comment by Matthww** [comment]
@strNophix
